raw_path: data/raw/NF-CICIDS2018-v3.csv
categorical_columns:
- IPV4_SRC_ADDR
- IPV4_DST_ADDR
confounders:
- IPV4_SRC_ADDR
- IPV4_DST_ADDR
- L4_SRC_PORT
- L4_DST_PORT
label_column: Label
benign_label: 0

autoencoder:
  latent_dim: 28
  hidden_dims:
  - 29
  - 28
  epochs: 50
  batch_size: 512
  dropout: 0.1097
  regularization: 0.024
